
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 13 11:19:13 COT 2015
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GUION = 3;
  public static final int error = 1;
  public static final int IGUAL = 2;
  public static final int NumeroReservadomovistar = 7;
  public static final int NumeroReservadoclaro = 6;
  public static final int DIGITO = 4;
  public static final int EOF = 0;
  public static final int NumeroReservadofijo = 5;
}

